version: '3.8'
services:
  database:
    container_name: db_retro_dev_journey
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-username}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-really_strong_password}
    ports:
      - "8420:27017"
    networks:
      - retro_dev_journey
    volumes:
      - mongo_data:/data/db
      #- ./database:/docker-entrypoint-initdb.d
  
  backend:
    container_name: go_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8421:8421"
    depends_on:
      - database
    environment:
    - APP_ENV=${APP_ENV:-local}
    networks:
      - retro_dev_journey
    volumes:
      - ./backend:/app

volumes:
  mongo_data:
    driver: local

networks:
  retro_dev_journey:
    name : retro_dev_journey
    driver: bridge