version: '3.8'
services:
  database:
    container_name: db_retro_dev_journey
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-username}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-really_strong_password}
    ports:
      - "8420:27017"
    networks:
      - retro_dev_journey
    volumes:
      - mongo_data:/data/db
      #- ./database:/docker-entrypoint-initdb.d
  
  backend:
    container_name: go_retro_dev_journey
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8421:8421"
    depends_on:
      - database
    environment:
    - APP_ENV=${APP_ENV:-prod}
    networks:
      - retro_dev_journey
      - nginx_reverse_proxy
  
  frontend:
    container_name: react_retro_dev_journey
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - APP_ENV=${APP_ENV:-prod}
    ports:
      - "8422:80"
    depends_on:
      - backend
    networks:
      - retro_dev_journey
    environment:
      - NODE_ENV=production

volumes:
  mongo_data:
    driver: local

networks:
  retro_dev_journey:
    name : retro_dev_journey
    driver: bridge
  nginx_reverse_proxy:
    external: true
